### ISSUE TITLE
dont work,stable version please!

### ISSUE THREAD

**Issue by 1322739583** [aneeshd16/vscode-opengrok#1]
dont work,stable version please!

**Comment by qu710458643** [comment]
The status of searching codebase with OpenGrok is comming,not done

**Comment by aneeshd16** [comment]
Hi @1322739583 @qu710458643 thanks for reporting. Can you please confirm if you have correctly set the `openGrok.serverSettings.rootUrl` and `openGrok.serverSettings.project` ?

**Comment by qu710458643** [comment]
> Hi @1322739583 @qu710458643 thanks for reporting. Can you please confirm if you have correctly set the `openGrok.serverSettings.rootUrl` and `openGrok.serverSettings.project` ?

Thank you! I will try it few days later!
